version: '3.8'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - alertmanager
      - cadvisor
    image: prom/prometheus:v2.27.1
    ports:
      - '9090:9090'
    restart: always
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

  alertmanager:
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    image: prom/alertmanager:v0.22.1
    ports:
      - '9093:9093'
    restart: always
    volumes:
      - ./config/alertmanager:/etc/alertmanager

  grafana:
    depends_on:
      - prometheus
    env_file:
      - ./config/grafana/grafana.env
    image: grafana/grafana:7.5.7
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  api:
    command: dotnet watch --project src/Imagine.Students.Api/Imagine.Students.Api.csproj run
    image: mcr.microsoft.com/dotnet/sdk:5.0
    ports:
      - '5000:5000'
    volumes:
      - .:/workspace
      - /workspace/src/Imagine.Students.Api/obj
      - /workspace/src/Imagine.Students.Api/bin
    working_dir: /workspace

  k6:
    entrypoint: /bin/sh
    command: -c 'k6 run -e BASE_URL=$${BASE_URL} tests/load/classroom-students-stress.js'
    environment:
      - BASE_URL=http://api:5000
    image: loadimpact/k6:0.32.0
    volumes:
      - .:/workspace
    working_dir: /workspace
