{
 "title": "Students API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"api\"}[2m]))\n/\nsum by (id) (\n  container_spec_cpu_shares{container_label_com_docker_compose_service=\"api\"}\n  /\n  container_spec_cpu_period{container_label_com_docker_compose_service=\"api\"}\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (container_memory_working_set_bytes{container_label_com_docker_compose_service=\"api\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"api\"}[5m])))*1000",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"api\"}[5m])))*1000",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(.75, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"api\"}[5m])))*1000",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"api\"}[5m])))*1000",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"api\",code=~\"[45]..\"}[1m])) / sum(rate(http_requests_received_total{job=\"api\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Request Duration Apdex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{job=\"api\",le=\"0.256\",code!~\"[45]..\"}[1m]))\n  +\n  sum(rate(http_request_duration_seconds_bucket{job=\"api\",le=\"1.024\",code!~\"[45]..\"}[1m]))\n) / 2 / sum(rate(http_request_duration_seconds_count[1m])) > 0 or vector(1)",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Requests (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total{job=\"api\"}[1m]))",
     "legendFormat": "{{code}}"
    },
    { "legendFormat": "{{code}}" }
   ]
  },
  {
   "title": "Operation Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(class, method) (student_api_operation_duration_seconds_sum / student_api_operation_duration_seconds_count * 1000) > 0",
     "legendFormat": "{{class}}#{{method}}"
    },
    {
     "expr": "http_request_duration_seconds_sum{code=\"200\"} / http_request_duration_seconds_count{code=\"200\"} * 1000",
     "legendFormat": "Request Duration"
    }
   ]
  }
 ]
}